// <auto-generated />
using System;
using Csegurancacap7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Csegurancacap7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240627020006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Csegurancacap7.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ActionTimestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Availability")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TeamId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Csegurancacap7.Models.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_END");

                    b.Property<string>("Observation")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<int>("Resolved")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DS_RESOLVIDO");

                    b.Property<int>("SOId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SO");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_SERVICE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_STATUS");

                    b.Property<int?>("TeamId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TEAM");

                    b.Property<int>("ZoneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONE");

                    b.HasKey("Id");

                    b.ToTable("T_OCORRENCIA");
                });

            modelBuilder.Entity("Csegurancacap7.Models.SO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<DateTime>("FactDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_FATO");

                    b.Property<DateTime?>("Hour")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_HORA");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_TIPO");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USER");

                    b.Property<int>("ZoneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONE");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("T_SO");
                });

            modelBuilder.Entity("Csegurancacap7.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TEAM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NM_DISPONIBILIDADE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_TEAM");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NM_QTD");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_ESPECIALIDADE");

                    b.Property<int>("ZoneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONE");

                    b.HasKey("Id");

                    b.ToTable("T_TEAM");
                });

            modelBuilder.Entity("Csegurancacap7.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_USER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_SENHA");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("T_USER");
                });

            modelBuilder.Entity("Csegurancacap7.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_CATEGORIA");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_ZONE");

                    b.HasKey("Id");

                    b.ToTable("T_ZONE");
                });

            modelBuilder.Entity("Csegurancacap7.Models.SO", b =>
                {
                    b.HasOne("Csegurancacap7.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csegurancacap7.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zone");
                });
#pragma warning restore 612, 618
        }
    }
}
